### ISSUE TITLE
Querying assignments when a class has no assignments.

### ISSUE THREAD

**Issue by ZacharyB19** [git-keeper/git-keeper#119]
Currently, git-keeper throws an exception when a class with no assignments has its assignments queried. To reproduce this issue, you would execute the following steps.

1. Have an existing faculty account properly add a new class.
2. On the client side, execute a gkeep query assignments from the new class.
3. Notice that an exception is thrown instead of returning nothing.

Possible solution to this issue:
- Have the query return a message to the client saying there are no assignments in the specified class.

**Comment by coderforlife** [comment]
This still seems to be an issue with the current running gkeepd at Moravian College.

**Comment by coderforlife** [comment]
Or, if it is a client issue, then with the newest client (0.2.2).

**Comment by coderforlife** [comment]
Traceback (most recent call last):
  File "/Users/bushj/dev/bin/gkeep", line 11, in <module>
    load_entry_point('git-keeper-client==0.2.2', 'console_scripts', 'gkeep')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gkeepclient/gkeep.py", line 376, in main
    take_action(parsed_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gkeepclient/gkeep.py", line 417, in take_action
    run_query(parsed_args.query_type, parsed_args.number_of_days)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gkeepclient/gkeep.py", line 334, in run_query
    list_assignments()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gkeepclient/client_function_decorators.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gkeepclient/client_function_decorators.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gkeepclient/queries.py", line 50, in list_assignments
    for assignment_name in sorted(info.assignment_list(class_name)):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gkeepcore/faculty_class_info.py", line 130, in assignment_list
    return list(self.info_dict[class_name]['assignments'])
KeyError: 'assignments'

**Comment by coderforlife** [comment]
I just checked this out in a bit more detail. This isn't a bug in 0.2.1 gkeep client but is a bug in 0.2.2 gkeep client. I checked on both macOS and Linux with fresh installations.

**Comment by coderforlife** [comment]
Correction: 0.2.1 seems to also have the bug, I actually think I may have had 0.2.0 previous when it was working.
